linux-yocto: drop 5.2 bbappend
The recipe for the 5.2 kernel has been dropped in this commit:
8efa405ee0ab9ae0e674fe8bc9551f4367b4c269

The corresponding .bbapend must be removed in order to fix this error:

ERROR: No recipes available for:
  meta-yocto-bsp/recipes-kernel/linux/linux-yocto_5.2.bbappend

Signed-off-by: Jean-Marie LEMETAYER <jean-marie.lemetayer@savoirfairelinux.com>